### ISSUE TITLE
Windows Phone 8.1 version

### ISSUE THREAD

**Issue by faisalr** [FlairWork/Quran360WindowsPhone#2]
Hello

I wonder if you want to make a Windows Phone 8.1 version from scratch using XML data instead of SDF with me?

**Comment by hanifw** [comment]
Is using Xml better than Sdf? How many xml files do we have to maintain on client side? Have you tried? 

-----Original Message-----

**Comment by faisalr** [comment]
No, but Sdf is not available in Windows Phone 8.1 only Xml or Json. You will need a lot of files if you want all the translations.

I did a lot of refactoring on the project.

**Comment by faisalr** [comment]
Look at my fork!

**Comment by faisalr** [comment]
We can grab all the Xml from Tanzil.net and disable topics and index.

**Comment by faisalr** [comment]
I missed with Telerik controls references so you might need to adjust it (delete it then add it again).

**Comment by hanifw** [comment]
hMm... We can also use sqlite instead of sql ce, i've used sqlite in Windows 8 version of the app (Win RT).

Index and topics need to be re-fetched from http://web.quran360.com 

Regards,

Muhammad Hanif Abdul Wahid
On Monday, May 19, 2014 7:44 AM, Faisal notifications@github.com wrote:

I missed with Telerik controls references so you might need to adjust it (delete it then add it again).
